{% set name = "libzenohc" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Workaround for faulty 1.0.0 tag, change once we tag has been fixed
  - url: https://github.com/eclipse-zenoh/zenoh-c/archive/bca57bb6e5a55421cc6ef20ddae5fd3cbb58c30c.tar.gz
    sha256: 365725dce66a577ad30e1308b8a0e25f7da36fc275f752d62032bb970dd13752
    patches:
      - 469.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - ninja
    - pkg-config
  host:
    - zenoh-rust-abi {{ version }}.*
test:
  commands:
    - test -f ${PREFIX}/lib/libzenohc${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\zenohc.dll.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\zenohc.dll exit 1  # [win]
    - cmake-package-check zenohc --targets zenohc::shared zenohc::lib
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/eclipse-zenoh/zenoh-c
  license: Apache-2.0 OR EPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: C API for Zenoh

extra:
  # Stick to the repo name for the feedstock name
  feedstock-name: zenoh-c
  recipe-maintainers:
    - traversaro
